# Generated by Django 5.2.1 on 2025-05-23 08:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('charges_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'verbose_name': 'Company Wallet',
                'verbose_name_plural': 'Company Wallets',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('direct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('matching', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='RankAndRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_no', models.IntegerField(default=0, verbose_name='Rank Number')),
                ('rank_name', models.CharField(max_length=30, verbose_name='Rank Name')),
                ('royalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Royalty Amount')),
                ('pairs', models.IntegerField(default=0, verbose_name='Pairs Required')),
                ('amount', models.IntegerField(default=0, verbose_name='Reward Amount')),
                ('reward_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reward Name')),
            ],
            options={
                'verbose_name': 'Rank and Reward',
                'verbose_name_plural': 'Ranks and Rewards',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], max_length=10, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('today_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('direct_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('level_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('resale_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('rank_no', models.PositiveIntegerField(default=0)),
                ('matching_pairs', models.PositiveIntegerField(default=0)),
                ('all_matching_pairs', models.PositiveIntegerField(default=0)),
                ('matching_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income from matching bonus.', max_digits=15)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wallet balance for the member.', max_digits=15)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount withdrawn.', max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('block', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('head_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_users', to=settings.AUTH_USER_MODEL)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_users', to=settings.AUTH_USER_MODEL)),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_users', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MLM Profile',
                'verbose_name_plural': 'MLM Profiles',
                'ordering': ['-joined_on'],
            },
        ),
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('direct_income', 'Direct Income'), ('level_income', 'Level Income'), ('matching_income', 'Matching Income'), ('resale_income', 'Resale Income')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_history', to='mlm_app.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='mlm_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='mlm_app.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlm_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('distributed_amount', models.FloatField(default=0)),
                ('resale_percentage', models.FloatField(default=0)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mlm_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_name', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('response_data', models.JSONField(default=dict)),
                ('recharge_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recharge_date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='mlm_app_mem_user_id_eb7ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['mobile_no'], name='mlm_app_mem_mobile__3b86f9_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['position'], name='mlm_app_mem_positio_8cb718_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='mlm_app_mem_status_cba108_idx'),
        ),
    ]
